title: fleetingXe's Journal of Floating Atoms
description: This is test.
theme: just-the-docs

url: 
  "fleetingXe":
    - "https://xe05.github.io/fleetingxe"

plugins:
  - jekyll-default-layout

aux_links:
  "itch.io":
    - "//fleetingxe.itch.io"

color_scheme: dark
