title: fleetingXe
description: My thoughts are made of atoms. They exist to be seen and read.
theme: just-the-docs
url: https://xe05.github.io/fleetingxe
plugins:
  - jekyll-default-layout
  - jekyll-seo-tag
heading_anchors: true

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_timestamp: true 

# uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
last_edit_time_format: "%b %e %Y at %I:%M %p"