title: fleetingXe
description: My thoughts are made of atoms. They exist to be seen and read.
theme: just-the-docs
url: https://xe05.github.io/fleetingxe
plugins:
  - jekyll-default-layout
  - jekyll-seo-tag
color_scheme: light
heading_anchors: true

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"