title: fleetingXe's Journal of Floating Atoms
description: This is test.
theme: just-the-docs

url: https://xe05.github.io/fleetingxe

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout